version: "3"

services:      
  api:
    build: ./ssrf-api/
    restart: unless-stopped
    ports:
      - '127.0.0.1:4000:3000'
  
  management:
    build: ./admin-app/
    restart: unless-stopped

networks:
  app:
    external: true
    name: app